name: Python Application CI/CD
on: [push, pull_request, workflow_dispatch]

jobs:
    build:
        runs-on: self-hosted
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
               python-version: "3.10"
               architecture: "x64"
               env:
               AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

    test:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Run tests
              run: |
                # Assuming you have tests defined, replace with actual test command
                echo "Running tests..."
                # Example: pytest

    deploy:
        needs: test
        runs-on: self-hosted
        steps:
             - name: Checkout code
               uses: actions/checkout@v2

             -  name: Set up Python
                uses: actions/setup-python@v2
                with:
                 python-version: "3.10"
                 architecture: "x64"
                 env:
                 AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache

             - name: Install dependencies
               run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
             - name: Run application
               run: |
                echo "Deploying application..."
                python app.py
            